tap_install:
    sensitive_values:
        shared:
            ingress_domain: ENC[AES256_GCM,data:nH8lTiewv/lKNi98onUPi6jDpcNit38BA87GYETBG5SEc7ZpPcB7ZJMAgdE=,iv:CeN0olSiWYgFrZwOEerf0uwPqL23ruXD6vB53TRivvQ=,tag:MCfm+vaHCEDI0F8AWQHurQ==,type:str]
            ingress_issuer: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140kfw9jqh7d63svrgf8rpjaf8mteg507va4s98pnjtl975qe6stqfpaxvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqemdNVFpsVWxENVRaRGQz
            Q1YzNXRVNGkyVExRanBnWXZKOUJlTDltMnlRClkzV2tlMlNlRnoyWVVIZmxWWVhN
            Z2xia05kelVCVHJqdEFUTEFiNytzRXMKLS0tIDJWWXJ5VXhGeTJvSExuTklmSmhj
            YVZtb0tsQndzRU1OR21Ma1dKYjNXY2sKpCyMtm0fBJOmOzCbu0JVT/lNslmin9vn
            EfQLx8nCFn4U3JtUoy4XQO9ljjF9b4RQzblSQk1BCo20spuWh2ez9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-21T07:10:06Z"
    mac: ENC[AES256_GCM,data:cjkCw3D1zJKYBeElNhN9pJqdLm6HKcY5nZCcR7Q8YfKUabfq56VRV8Bq6rpLHTkSgYYCc19axZiVEWdNsYXnJzD/FbuRo/EIuZWjO6PmYu5sa7ameIHRGt8p9N23ISXXJZzlrMyN46JjqQLbfigaUIG80yNlFCflgCBZbfsBbzs=,iv:TGlpmbPsm1Leru5qZPSq/rhst8WxwkpfUMf6fkR4Ol4=,tag:71/N83m9fqOvY+hJpuvZyg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
